services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr-code-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "5173:5173"
    networks:
      - pr-code-network
    depends_on:
      - redis
      - mysql

  nginx:
    image: nginx:alpine
    container_name: pr-code-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pr-code-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: pr-code-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pr_code
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: pr_code
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - pr-code-network

  redis:
    image: redis:alpine
    container_name: pr-code-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pr-code-network

networks:
  pr-code-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

